### ISSUE TITLE
Submit not working

### ISSUE THREAD

**Issue by critzo** [throneless-tech/piecewise-saas#17] opened 2020-09-09 15:47 UTC
In Firefox, after completing the survey and the test is complete, I click Submit but nothing happens.

**Comment by jheretic** [comment] 2020-09-09 17:32
This is caused by a difference in the return type of complex JSON structures between sqlite and postgres. The survey submission does still seem to be added to the database, it's in parsing the `POST` return value that it bombs out. Should be fixed in https://github.com/throneless-tech/piecewise/pull/8

**Closed** 2020-09-11 16:59 UTC
Labels: bug, high
